### ISSUE TITLE
New version release needed because of the new century characters

### ISSUE THREAD

**Issue by Luoti** [devsmo/php-hetu#3]
First of all, thank you for your work on this package!

Would it be possible for you to push out a new release on this package, so the new century characters for 2023 would be available on an actual release?

Thanks!

**Comment by devsmo** [comment]
Hi,
It should already support the new century codes: A B C D E and F for 2000s and Y C W V and Y for 1900s.
Is this what you refer to?

**Comment by Luoti** [comment]
Yes!
I know the functionality has been merged a year ago, but the newest package version 1.1.0 in [Packagist](https://packagist.org/packages/devsmo/php-hetu#v1.1.0) shows that it has been release 2017-10-29 15:18 UTC. With a new release we could lock the package version to our composer.json files.

**Comment by devsmo** [comment]
Alright, I gotcha.
Now there should be a new version, v1.2.0
Hope this helps!

**Comment by Luoti** [comment]
Thank you! 👍
